packages:
  - playground/*

catalogMode: prefer

catalogs:
  cli:
    automd: ^0.4.3
    changelogen: ^0.6.2
    obuild: ^0.4.33
    oxfmt: ^0.32.0
    oxlint: ^1.58.0
    typescript: ~5.9.3
    vite: ^7.3.1
  testing:
    "@vitest/coverage-v8": ^4.1.2
    vitest: ^4.1.2
  types:
    "@types/node": ^25.5.0

shellEmulator: true

trustPolicy: no-downgrade
