packages:
  - playground/*

catalogMode: prefer

catalogs:
  cli:
    automd: ^0.4.3
    changelogen: ^0.6.2
    obuild: ^0.4.31
    oxfmt: ^0.32.0
    oxlint: ^1.49.0
    typescript: ~5.9.3
    vite: ^7.3.1
  testing:
    "@vitest/coverage-v8": 4.0.18
    vitest: ^4.0.18
  types:
    "@types/node": ^25.3.0

# ignoreWorkspaceRootCheck: true

shellEmulator: true

trustPolicy: no-downgrade
